name: ZAP Baseline Scan

on:
  pull_request:
      branches:
          - master
      paths-ignore:
          - '*.md'
          - 'LICENSE'
          - 'data/static/i18n/*.json'
          - 'frontend/src/assets/i18n/*.json'
  workflow_dispatch:
  schedule:
    - cron:  '0 18 * * 6'
    
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan Juice Shop preview instance on Heroku
    steps:
      - name: Check out Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          ref: develop
      - name: ZAP Scan
        uses: zaproxy/action-baseline@7c4deb10e6261301961c86d65d54a516394f9aed # v0.14.0
        with:
          target: 'http://13.52.216.165/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a -j'
      - name: Upload ZAP SARIF file as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-results
          path: results.sarif
